import os
from datetime import datetime

CONVERSATIONS_DIR = "conversations"

"""This file is generated by Claude sonnet 4.6"""

def _next_file_number(role: str) -> int:
    os.makedirs(CONVERSATIONS_DIR, exist_ok=True)
    existing = [
        f for f in os.listdir(CONVERSATIONS_DIR)
        if f.startswith(role) and f.endswith(".md")
    ]
    print(existing)
    return len(existing) + 1


def save_conversation(role: str, conversation: list[dict]) -> str:
    n = _next_file_number(role)
    filename = os.path.join(CONVERSATIONS_DIR, f"{role}{n}.md")

    lines = [
        f"# {role} Interview — Session {n}",
        f"*{datetime.now().strftime('%Y-%m-%d %H:%M')}*",
        "",
    ]

    for entry in conversation:
        speaker = entry["speaker"].capitalize()
        lines.append(f"**{speaker}:** {entry['message']}")
        lines.append("")

    with open(filename, "w") as f:
        f.write("\n".join(lines))

    return filename
